root: "/data/active/hmax/MARVWY_RESTORED/20220721_ZE4i2_aligned1"
# root: "M:\\marvwy\\20220721_ZE4i2_aligned"

image_dir: "imgs"

output_dir: "features_tcorr"

level: 1

features:
  hierarchy:
  - label_image: "cells"
    parent_label_images:
      -  "embryoRaw"

  - label_image: "cyto"
    parent_label_images:
      -  "cells"

  - label_image: "nucleiRaw3"
    parent_label_images:
      -  "embryoRaw"
      -  "cells"

  label:
  - labelss:
    - "nucleiRaw3"

  - labelss:
    - "cells"
    - "embryoRaw"
    props:
    - "!FeretDiameter"

  intensity:
  - labelss:
    - "nucleiRaw3"
    - "cells"
    - "cyto"
    channels:
    - '*'
  
  correlation:
  - labelss:
    - 'nucleiRaw3'
    channel_pairs:
    - channel_0: "DAPI.1"
      channel_1: "DAPI.0"
    - channel_0: "DAPI.1"
      channel_1: "DAPI.2"
    - channel_0: "DAPI.1"
      channel_1: "DAPI.3"
    props:
    - "PearsonR"
    - "SpearmanR"
    - "KendallTau"
    

  density:
  - labelss:
    - "nucleiRaw3"
    delaunay_mask_labels:
    - "embryoRaw"

  - labelss:
    - "cells"
    delaunay_mask_labels:
    - "embryoRaw"
    params:
      radius: []
      distance_to_closest_neighbor: False
      knn_distance: []


  distance:
  - labelss:
    - "nucleiRaw3"
    label_objects_to:
    - label_image: "embryoRaw"
      label: 1
    distance_transforms:
    - "DistanceToBorder"
    - "DistanceAlongZ"
    props:
    - "Centroid"
    - "Minimum"
    - "Maximum"


intensity_correction:
  t_decay_models: "/data/active/hmax/MARVWY_RESTORED/20220721_ZE4i2_aligned1/models_v2/t_decay/correction_factors.parquet"
  # t_decay_correction_factor_column: "correctionFactor-Exp"
  z_decay_add_model_name_to_feature_path: true
  z_decay_models: "/data/active/hmax/MARVWY_RESTORED/20220721_ZE4i2_aligned1/models_v2/z_decay/ExpNoOffset(features=Centroid-z, loss=huber)"
  z_decay_two_step_label: "embryoRaw"
  z_decay_default_models: null
