# %%
import copy
import pickle
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Sequence, TypeAlias

import dask.array as da
import numpy as np
import pandas as pd
from numpy.typing import NDArray
from scipy.optimize import curve_fit
from typing_extensions import Self, Unpack

from zfish.features.types import SpatialImage

Parameters: TypeAlias = tuple[float, ...]
ModelCallable: TypeAlias = Callable[[NDArray[Any], Unpack[Parameters]], NDArray[Any]]
ArrayLike: TypeAlias = NDArray[Any] 

# Parameters: TypeAlias = Sequence[float]
# ModelCallable: TypeAlias = Callable[[NDArray[Any], Parameters], NDArray[Any]]


def linear_model(X: NDArray[Any], intercept: float, *coef: float) -> NDArray[Any]:
    """Linear model of the form:
    y = a1 * x1 + a2 * x2 ... + an * xn + b"""
    return intercept + np.sum(X * coef, axis=1)


def exponential_model_glm(X: NDArray[Any], A0: float, *coef: float) -> NDArray[Any]:
    """Exponential model of the form:
    y = A0 * (np.exp(b1 * x1) + np.exp(b2 * x2) + ... + np.exp(bn * xn))"""
    return A0 * np.sum(np.exp(X * coef), axis=1)


def exponential_model_with_offset(
    X: NDArray[Any], A0: float, C: float, *coef: float
) -> NDArray[Any]:
    """Exponential model with an offset term.
    y = A0 * (np.exp(b1 * x1) + np.exp(b2 * x2) + ... + np.exp(bn * xn)) + C"""
    return A0 * np.sum(np.exp(X * coef), axis=1) + C

# TODO: Currently str(Model) is almost the same as repr(Model), either have a more
# concice __str__ representation or go all in with __repr__.
@dataclass
class Model(ABC):
    _model: ModelCallable = field(repr=False)
    _params: Parameters | None = field(default=None, repr=False)
    _feature_names: list[str] | None = field(default=None, repr=True)
    _target_name: str | None = field(default=None, repr=True)
    loss: str = "linear"

    @abstractmethod
    def fit(self, X: NDArray[Any], y: NDArray[Any]) -> Self:
        if isinstance(X, pd.DataFrame):
            self._feature_names = list(X.columns)
        if isinstance(y, pd.Series):
            self._target_name = y.name

    @property
    @abstractmethod
    def y_intercept(self) -> float:
        pass

    @property
    def params(self) -> Parameters:
        if self._params is None:
            raise RuntimeError(
                "Can't access `self.params` befor the model has been fitted!"
            )
        return self._params

    def predict(self, X: NDArray[Any]) -> NDArray[Any]:
        return self._model(X, *self.params)
    
    def grid_predict(self, Xx: tuple[NDArray[Any], NDArray[Any]]) -> NDArray[Any]:
        assert len(Xx) == 2 and isinstance(Xx, tuple | list), "pass a list generated by `np.meshgrid` on which to evaluate."
        shape = Xx[0].shape
        X = np.vstack([Xx[0].flatten(), Xx[1].flatten()]).T
        y = self.predict(X)
        return y.reshape(shape)

    def _correction_factor(self, X: NDArray[Any]) -> NDArray[Any]:
        return 1 / self.predict(X) * self.y_intercept
    
    def _grid_correction_factor(self, Xx: tuple[NDArray[Any], NDArray[Any]]) -> NDArray[Any]:
        return 1 / self.grid_predict(Xx) * self.y_intercept

    def correct(self, X: NDArray[Any], y: NDArray[Any]) -> NDArray[Any]:
        return y * self._correction_factor(X)
    
    def grid_correct(self, Xx: tuple[NDArray[Any], NDArray[Any]], yy: NDArray[Any]) -> NDArray[Any]:
        return yy * self._grid_correction_factor(Xx)

    def save(
        self, file_name: str | None = None, directory: str | Path = Path("."), mode="xb"
    ) -> None:
        if file_name is None:
            # file_name = f"{self.__class__.__name__}"
            file_name = str(self)

        full_out_file = Path(directory) / f"{file_name}.pkl"
        print(f"Saving model to {full_out_file}")
        full_out_file.parent.mkdir(exist_ok=True)
        with open(full_out_file, mode=mode) as f:
            pickle.dump(self, f)

    @classmethod
    def load(cls, full_file_path: str | Path):
        with open(full_file_path, "rb") as f:
            model = pickle.load(f)
        return model

    # def __repr__(self) -> str:
    # class_name = self.__class__.__name__
    # if self._params is None:
    #     return f"{class_name}: not fitted."
    # return f"{class_name}: {self.params}"

    def __str__(self) -> str:
        class_name = self.__class__.__name__
        if self._params is None:
            return f"{class_name}(loss={self.loss!r}): not fitted."
        return f"{class_name}(loss={self.loss!r}, features={self._feature_names})"


@dataclass
class Linear(Model):
    _model: ModelCallable = field(default=linear_model, repr=False)

    def fit(self, X: NDArray[Any], y: NDArray[Any]) -> Self:
        super().fit(X, y)
        self._params, _ = curve_fit(
            self._model, X, y, loss=self.loss, method="trf", p0=np.ones(X.shape[1] + 1)
        )
        return self

    @property
    def y_intercept(self) -> float:
        return self.params[0]


@dataclass
class ExpFitLinear(Model):
    _model: ModelCallable = field(default=exponential_model_glm, repr=False)

    def fit(self, X: NDArray[Any], y: NDArray[Any]):
        super().fit(X, y)
        # Fit a linear model on log-transformed data.
        lin_params, _ = curve_fit(
            linear_model,
            X,
            np.log(np.clip(y, 1e-6, None)),
            loss=self.loss,
            method="trf",
            p0=np.ones(X.shape[1] + 1),
        )
        # Transform the first coefficient by applying `np.exp`
        self._params = tuple([np.exp(lin_params[0]), *lin_params[1:]])
        return self

    @property
    def y_intercept(self) -> float:
        return self.params[0] * (len(self.params) - 1)


@dataclass
class ExpNoOffset(Model):
    _model: ModelCallable = field(default=exponential_model_glm, repr=False)

    def fit(self, X: NDArray[Any], y: NDArray[Any]):
        super().fit(X, y)
        # Fit an `ExpFitLinear` to find initialization parameters -> better convergence.
        mdl = ExpFitLinear().fit(X, y)
        # Then fit the actual model.
        self._params, _ = curve_fit(
            self._model, X, y, loss=self.loss, method="trf", p0=mdl.params
        )
        return self

    @property
    def y_intercept(self) -> float:
        return self.params[0] * (len(self.params) - 1)


@dataclass
class Exp(Model):
    _model: ModelCallable = field(default=exponential_model_with_offset, repr=False)
    offset_init: int = field(default=0, repr=False)
    enforce_positive_offset: bool = field(default=False, repr=True)

    def fit(self, X: NDArray[Any], y: NDArray[Any]) -> Self:
        super().fit(X, y)
        # Estimate initial parameters using an `ExponentialModelNoOffset`.
        mdl = ExpNoOffset().fit(X, y)
        p0 = np.array([mdl.params[0], self.offset_init, *mdl.params[1:]])
        lower_bounds = np.array([-np.inf for _ in range(len(p0))])
        if self.enforce_positive_offset:
            lower_bounds[1] = 0.0
        upper_bounds = np.array([np.inf for _ in range(len(p0))])
        bounds = (lower_bounds, upper_bounds)
        # Then fit the actual model.
        self._params, _ = curve_fit(
            self._model, X, y, loss=self.loss, method="trf", p0=p0, bounds=bounds
        )
        return self

    @property
    def y_intercept(self) -> float:
        return self.params[0] * (len(self.params) - 2) + self.params[1]

    def __str__(self) -> str:
        class_name = self.__class__.__name__
        if self._params is None:
            return f"{class_name}(loss={self.loss!r}): not fitted."
        return f"{class_name}(loss={self.loss!r}, features={self._feature_names}, p_offset={self.enforce_positive_offset!r})"


def fit_model_to_df(
    df: pd.DataFrame,
    channel: str,
    model: Model,
    X_columns: Sequence[str] = ("MediumPath", "EmbryoPath"),
    y_column: str = "Mean",
    n_samples: int | None = None,
    in_place: bool = False,
) -> Model | None:
    for column in list(X_columns) + [y_column]:
        assert column in df, f"column `{column}` not in `df`"

    if in_place:
        model_copy = model
    else:
        model_copy = copy.deepcopy(model)

    df_channel = df[df.channel == channel]
    if n_samples:
        df_sample = df_channel.sample(n_samples)
    else:
        df_sample = df_channel
    X = df_sample[list(X_columns)]
    y = df_sample[y_column]
    try:
        model_copy.fit(X, y)
    except RuntimeError as e:
        print(e)
        print(f"no convergance for `{str(model)}` in channel `{channel}`")
        return None
    return model_copy


def apply_model_to_channel(
    model: Model,
    channel_si: SpatialImage,
    label_si: SpatialImage | None = None,
) -> SpatialImage:
    if model._feature_names == ["Centroid-z"]:
        return (
            channel_si
            * model._correction_factor(channel_si.coords["z"].expand_dims(["_"], -1))
        ).rename("image")

    elif model._feature_names == ["MediumPath", "EmbryoPath"]:
        assert (
            label_si is not None
        ), "Provide embryo segmentation for 2-step correction."
        embryo_path_si = (label_si * label_si.meta.scale[0]).cumsum(dim="z")
        medium_path_si = (~label_si.astype(bool) * label_si.meta.scale[0]).cumsum(
            dim="z"
        )
        X = da.stack([medium_path_si.data.flatten(), embryo_path_si.data.flatten()]).T
        # X = np.concatenate([medium_path_si, embryo_path_si]).reshape(2, -1).T
        correction_factors = model._correction_factor(X).T.reshape(channel_si.shape)
        return (channel_si * correction_factors).rename("image")

    else:
        raise ValueError(f"Unkown model feature names: {model._feature_names=}")


class NoiseModel(ABC):
    @abstractmethod
    def transform(self, X: NDArray[Any]) -> NDArray[Any]:
        pass


class NoNoise(NoiseModel):
    def transform(self, X: NDArray[Any]) -> NDArray[Any]:
        return X


@dataclass
class GaussianNoise(NoiseModel):
    apply: Callable
    sigma: float = 1

    def transform(self, X: NDArray[Any]) -> NDArray[Any]:
        noise = np.random.randn(X.shape) * self.sigma
        return self.apply(X, noise)


@dataclass
class AdditiveGaussianNoise(GaussianNoise):
    apply: Callable = np.add


@dataclass
class MultiplicativeGaussianNoise(GaussianNoise):
    apply: Callable = np.multiply


@dataclass
class DataGenerator:
    model: Model
    noise_model: NoiseModel


# %%
if __name__ == "__main__":
    # %%

    mdl = Linear()
    out_file = mdl.save(file_name="test")